name: Metrics

on:
  schedule:
    - cron: "0 * * * *"  # Corre cada hora
  workflow_dispatch:     # Permite correrlo manualmente
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: AzzADesigns
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Argentina/Buenos_Aires
          filename: metrics.svg
          output_action: commit
          output_branch: generated
